### Get Token from Firebase
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyDSp6W4c4CDjEF__tbXAy1706O1QNPJ5Os
Content-Type: application/json

{
  "email": "tragopoulos@icloud.com",
  "password": "niniboo.5U",
  "returnSecureToken": true
}

### Create Account
POST https://c2q2xhxtpb3qf57rzs43zq6k2m.apigateway.eu-frankfurt-1.oci.customer-oci.com/v1/account
Content-Type: application/json
X-Client-Platform: web
X-Device-Signature:eyJsb2NhbGUiOnsibGFuZ3VhZ2VUYWciOiJlbi1VUyIsInJlZ2lvbkNvZGUiOiJVUyIsImN1cnJlbmN5Q29kZSI6bnVsbCwiY3VycmVuY3lTeW1ib2wiOm51bGwsImRlY2ltYWxTZXBhcmF0b3IiOiIuIiwiZGlnaXRHcm91cGluZ1NlcGFyYXRvciI6IiwiLCJ0ZW1wZXJhdHVyZVVuaXQiOiJmYWhyZW5oZWl0IiwidGV4dERpcmVjdGlvbiI6bnVsbH0sImNhbGVuZGFyIjp7ImNhbGVuZGFyVHlwZSI6ImdyZWdvcnkiLCJmaXJzdFdlZWtkYXlOYW1lIjpudWxsLCJ0aW1lem9uZSI6IkV1cm9wZS9BdGhlbnMiLCJ1c2VzMjRob3VyQ2xvY2siOm51bGx9LCJkZXZpY2VfdHlwZSI6ImRlc2t0b3AiLCJtYW51ZmFjdHVyZXIiOm51bGwsImJyYW5kIjpudWxsLCJtb2RlbF9uYW1lIjpudWxsLCJkZXZpY2VfbmFtZSI6bnVsbCwiaXNfcGh5c2ljYWxfZGV2aWNlIjp0cnVlLCJjcHVfYXJjaGl0ZWN0dXJlcyI6WyJhbWQ2NCJdLCJ0b3RhbF9tZW1vcnkiOjg1ODk5MzQ1OTIsInllYXJfY2xhc3MiOm51bGwsIm9zX25hbWUiOiJXaW5kb3dzIiwib3NfdmVyc2lvbiI6IjEwIiwib3NfYnVpbGRfaWQiOm51bGx9
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg1NGFhNGMyM2VkZTdiOGNhODc1OWZiMDZlNmExZDU4OTI0MjVkMDYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3luY3JvaW5zcGVjdCIsImF1ZCI6InN5bmNyb2luc3BlY3QiLCJhdXRoX3RpbWUiOjE3ODAzMTAxODMsInVzZXJfaWQiOiJjd0pVd0RoRWhiZXYwSDJMTlgyMER1Q3FqVk4yIiwic3ViIjoiY3dKVXdEaEVoYmV2MEgyTE5YMjBEdUNxalZOMiIsImlhdCI6MTc4MDMxMDE4MywiZXhwIjoxNzgwMzEzNzgzLCJlbWFpbCI6InRyYWdvcG91bG9zQGljbG91ZC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidHJhZ29wb3Vsb3NAaWNsb3VkLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Z2nfpQdCifxZCfEmvpnmGxUZ6QsN76r1Or5SFTudgQTFQemHgHdQB-ZWaTYVyxWAqwcdBQjMiWp2ceqYmOCBR0lnfMZObIh-SjMm8e2Tus1E2SqpmT1h-KY5nPelV_6WjdrzoD8PAuWe5dqN0xx2NJ8FJIC4j9b-XTEo5QNFSGIABS5I4yRP8o2ik3WXID-Z_ToU_cpKc7O-1ghID5GuVKINsnfv-q54oyl69kPRvYTT48jd8UDydPzOqTKTggSg-yeOOdv2hHcWGj12iicezU0GSLGJHqseFcEKo8AKMIoJ-AwsPKD3xuV66ut-JFT2wpzIEqpb6TJ02VwURtnG-Q

{
  "alpha":"alpha",
  "beta":"beta",
  "gama": "gama",
  "delta": "delta"
}

### multipart/form-data
POST https://c2q2xhxtpb3qf57rzs43zq6k2m.apigateway.eu-frankfurt-1.oci.customer-oci.com/v1/account
X-Client-Platform: web
X-Device-Signature:eyJsb2NhbGUiOnsibGFuZ3VhZ2VUYWciOiJlbi1VUyIsInJlZ2lvbkNvZGUiOiJVUyIsImN1cnJlbmN5Q29kZSI6bnVsbCwiY3VycmVuY3lTeW1ib2wiOm51bGwsImRlY2ltYWxTZXBhcmF0b3IiOiIuIiwiZGlnaXRHcm91cGluZ1NlcGFyYXRvciI6IiwiLCJ0ZW1wZXJhdHVyZVVuaXQiOiJmYWhyZW5oZWl0IiwidGV4dERpcmVjdGlvbiI6bnVsbH0sImNhbGVuZGFyIjp7ImNhbGVuZGFyVHlwZSI6ImdyZWdvcnkiLCJmaXJzdFdlZWtkYXlOYW1lIjpudWxsLCJ0aW1lem9uZSI6IkV1cm9wZS9BdGhlbnMiLCJ1c2VzMjRob3VyQ2xvY2siOm51bGx9LCJkZXZpY2VfdHlwZSI6ImRlc2t0b3AiLCJtYW51ZmFjdHVyZXIiOm51bGwsImJyYW5kIjpudWxsLCJtb2RlbF9uYW1lIjpudWxsLCJkZXZpY2VfbmFtZSI6bnVsbCwiaXNfcGh5c2ljYWxfZGV2aWNlIjp0cnVlLCJjcHVfYXJjaGl0ZWN0dXJlcyI6WyJhbWQ2NCJdLCJ0b3RhbF9tZW1vcnkiOjg1ODk5MzQ1OTIsInllYXJfY2xhc3MiOm51bGwsIm9zX25hbWUiOiJXaW5kb3dzIiwib3NfdmVyc2lvbiI6IjEwIiwib3NfYnVpbGRfaWQiOm51bGx9
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNiMDk1NzQ3YmY4MzMxZWE0YWQ1M2YzNzBjNjMyNjAxNzliMGQyM2EiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3luY3Jvc29jaWFscHJvZCIsImF1ZCI6InN5bmNyb3NvY2lhbHByb2QiLCJhdXRoX3RpbWUiOjE3NzY1MTUzMTAsInVzZXJfaWQiOiJZRjF0SjVCYU5LUkZlT1Rxd21tb1A1ZG5ZVG8yIiwic3ViIjoiWUYxdEo1QmFOS1JGZU9UcXdtbW9QNWRuWVRvMiIsImlhdCI6MTc3NjUxNTMxMCwiZXhwIjoxNzc2NTE4OTEwLCJlbWFpbCI6InRyYWdvcG91bG9zQGljbG91ZC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidHJhZ29wb3Vsb3NAaWNsb3VkLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.XH11EJ7_rsqpG7mDXiZr1SschcP0f-vIDJJcB6h4x9vDbKJ6UU31Sv9y18x0Ui3-LOgH07a3VS_ft966o-afG54WOGkgj8xvu927JBYzL7nMj8z2TaxEoSxME__yssr72jjGFN6j8c2B3DTuKN0CQl5kMy9JGCmBjMXzBcVDfh8_2g2JUvR06i5x7m8zLAUb5odevokDNd9Nt6em4CoS7_Odovtw67jisFyxUuxIInmGc_-L7Gu-wWf2DzFEwzYN6Ge35Gc50VGCqkq7H0vgC8r5v_lJzgpebGuzUnoMgHMIp0eDVqlgYOIA3lRf-piqq4UcFLDQeIdJJlYHIkHOBw
Content-Type: multipart/form-data; boundary=**SyncroSocialBoundary**

--**SyncroSocialBoundary**
Content-Disposition: form-data; name="body"
Content-Type: application/json

{
  "alpha":"alpha",
  "beta":"beta",
  "gama": "gama",
  "delta": "delta"
}

--**SyncroSocialBoundary**
Content-Disposition: form-data; name="file"; filename="log.txt"
Content-Type: text/plain

< C:/Projects/log.txt

--**SyncroSocialBoundary**--